//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tema4MvcApp.LoginWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice/", ConfigurationName="LoginWebService.LoginWS")]
    public interface LoginWS {
        
        // CODEGEN: Generating message contract since element name username from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice/LoginWS/RegisterRequest", ReplyAction="http://webservice/LoginWS/RegisterResponse")]
        Tema4MvcApp.LoginWebService.RegisterResponse Register(Tema4MvcApp.LoginWebService.RegisterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice/LoginWS/RegisterRequest", ReplyAction="http://webservice/LoginWS/RegisterResponse")]
        System.Threading.Tasks.Task<Tema4MvcApp.LoginWebService.RegisterResponse> RegisterAsync(Tema4MvcApp.LoginWebService.RegisterRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice/LoginWS/LoginRequest", ReplyAction="http://webservice/LoginWS/LoginResponse")]
        Tema4MvcApp.LoginWebService.LoginResponse Login(Tema4MvcApp.LoginWebService.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice/LoginWS/LoginRequest", ReplyAction="http://webservice/LoginWS/LoginResponse")]
        System.Threading.Tasks.Task<Tema4MvcApp.LoginWebService.LoginResponse> LoginAsync(Tema4MvcApp.LoginWebService.LoginRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Register", Namespace="http://webservice/", Order=0)]
        public Tema4MvcApp.LoginWebService.RegisterRequestBody Body;
        
        public RegisterRequest() {
        }
        
        public RegisterRequest(Tema4MvcApp.LoginWebService.RegisterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class RegisterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public RegisterRequestBody() {
        }
        
        public RegisterRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterResponse", Namespace="http://webservice/", Order=0)]
        public Tema4MvcApp.LoginWebService.RegisterResponseBody Body;
        
        public RegisterResponse() {
        }
        
        public RegisterResponse(Tema4MvcApp.LoginWebService.RegisterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class RegisterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public RegisterResponseBody() {
        }
        
        public RegisterResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://webservice/", Order=0)]
        public Tema4MvcApp.LoginWebService.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(Tema4MvcApp.LoginWebService.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://webservice/", Order=0)]
        public Tema4MvcApp.LoginWebService.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(Tema4MvcApp.LoginWebService.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LoginWSChannel : Tema4MvcApp.LoginWebService.LoginWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginWSClient : System.ServiceModel.ClientBase<Tema4MvcApp.LoginWebService.LoginWS>, Tema4MvcApp.LoginWebService.LoginWS {
        
        public LoginWSClient() {
        }
        
        public LoginWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tema4MvcApp.LoginWebService.RegisterResponse Tema4MvcApp.LoginWebService.LoginWS.Register(Tema4MvcApp.LoginWebService.RegisterRequest request) {
            return base.Channel.Register(request);
        }
        
        public string Register(string username, string password) {
            Tema4MvcApp.LoginWebService.RegisterRequest inValue = new Tema4MvcApp.LoginWebService.RegisterRequest();
            inValue.Body = new Tema4MvcApp.LoginWebService.RegisterRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            Tema4MvcApp.LoginWebService.RegisterResponse retVal = ((Tema4MvcApp.LoginWebService.LoginWS)(this)).Register(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tema4MvcApp.LoginWebService.RegisterResponse> Tema4MvcApp.LoginWebService.LoginWS.RegisterAsync(Tema4MvcApp.LoginWebService.RegisterRequest request) {
            return base.Channel.RegisterAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tema4MvcApp.LoginWebService.RegisterResponse> RegisterAsync(string username, string password) {
            Tema4MvcApp.LoginWebService.RegisterRequest inValue = new Tema4MvcApp.LoginWebService.RegisterRequest();
            inValue.Body = new Tema4MvcApp.LoginWebService.RegisterRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((Tema4MvcApp.LoginWebService.LoginWS)(this)).RegisterAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tema4MvcApp.LoginWebService.LoginResponse Tema4MvcApp.LoginWebService.LoginWS.Login(Tema4MvcApp.LoginWebService.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public string Login(string username, string password) {
            Tema4MvcApp.LoginWebService.LoginRequest inValue = new Tema4MvcApp.LoginWebService.LoginRequest();
            inValue.Body = new Tema4MvcApp.LoginWebService.LoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            Tema4MvcApp.LoginWebService.LoginResponse retVal = ((Tema4MvcApp.LoginWebService.LoginWS)(this)).Login(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tema4MvcApp.LoginWebService.LoginResponse> Tema4MvcApp.LoginWebService.LoginWS.LoginAsync(Tema4MvcApp.LoginWebService.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tema4MvcApp.LoginWebService.LoginResponse> LoginAsync(string username, string password) {
            Tema4MvcApp.LoginWebService.LoginRequest inValue = new Tema4MvcApp.LoginWebService.LoginRequest();
            inValue.Body = new Tema4MvcApp.LoginWebService.LoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((Tema4MvcApp.LoginWebService.LoginWS)(this)).LoginAsync(inValue);
        }
    }
}
